server:
  port: 9000
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080"
            allowedMethods:
              - GET
              - POST
      routes:
        - id: service-blog
          uri: http://localhost:9001
          predicates:
            - Path=/article/**,/articleCategory/**,/articleTag/**,/category/**,/image/**,/tag/**
        - id: service-user
          uri: http://localhost:9002
          predicates:
            - Path=/user/**