spring:
  application:
    name: service-blog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ny02164215
    url: jdbc:mysql://localhost:3306/personal_blog_system_blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  web:
    resources:
      static-locations: classpath:/imgs
  mvc:
    static-path-pattern: /**
  servlet:
    multipart:
      max-file-size: 20MB
  cloud:
    nacos:
      discovery:
        server-addr: 123.57.71.52:8848
  jackson:
    date-format: java.text.SimpleDateFormat
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8001
